### ISSUE TITLE
Add ability to register PostCSS plugins

### ISSUE THREAD

**Issue by gijsroge** [Intracto/buildozer#18]
It would be nice if the user could use other PostCSS plugins other than the default ones.

For example if you would like to [inline svg's](https://github.com/TrySound/postcss-inline-svg) it's currently not possible.

PR incoming.

**Comment by MartijnCuppens** [comment]
Reopening this due https://github.com/Intracto/buildozer/pull/19#issuecomment-537189759

**Comment by gijsroge** [comment]
Opened new pr #32 32

**Comment by MartijnCuppens** [comment]
Closed by #32
