### ISSUE TITLE
Should we put opinionated PostCSS plugins as defaults?

### ISSUE THREAD

**Issue by gijsroge** [Intracto/buildozer#20]
Currently the PostCSS configuration contains a few plugins as default.

- Autoprefixer
- cssnano
- RFS

As good and as useful RFS is, I'm wondering if this should be included in the default build? 

If for example someone wants to use Buildozer but does not have the need for RFS it will still be used and executed.

More specifically lets say the user uses some Sass framework that already defined the mixin `font-size()` this would cause unexpected behavior.

You could say the same of Autoprefixer and cssnano but I think this is different because they don't introduce new features/behavior rather they just provide compatibility and optimizations.

This all depends on if we want to be an opinionated build system or not. Just something we should consider imo.

**Comment by MartijnCuppens** [comment]
> As good and as useful RFS is, I'm wondering if this should be included in the default build?

This was added because the initial idea was to create an opinionated base setup for Intracto, but yeah, it exceeds the idea of 'just a build' so I'm fine removing it by default if we can easily re-add it with https://github.com/Intracto/buildozer/pull/19 (would be a BC though).

**Comment by gijsroge** [comment]
> This was added because the initial idea was to create an opinionated base setup for Intracto
Yeah thats what I figured.

> (would be a BC though).
yeah definitely.
