### ISSUE TITLE
Callbacks return too fast

### ISSUE THREAD

**Issue by MartijnCuppens** [Intracto/buildozer#22]
The callbacks in the gulp tasks just run when when all tasks are initiated, not when they are finished. For example for the CSS:
https://github.com/Intracto/buildozer/blob/c80fc04760dbf033946a4f015ac7390a39f0458d/lib/gulp/css.js#L12-L17

We'll probably need to add all the tasks to an array and return the callback only when every task is finished.

Same issue for js and img tasks.

**Comment by MartijnCuppens** [comment]
I tried this, with no success:
```js
function css(cb) {
  config.scss.forEach(async scss => {
    await cssCompile({src: config.src_base_path + scss.src, dest: config.dest_base_path + scss.dest});
  });
  cb();
}
```
Also tried to add each `cssCompile` function to an array which is returned in the end, also didn't work. I haven't figured out how all these callbacks work exactly, if there's anyone who can help me out with this, feel free to contribute ❤️

**Comment by gijsroge** [comment]
Could you elaborate what this issue causes? Does it trigger a reload to fast or?
