### ISSUE TITLE
When you trigger an error in the sass task the watcher gets stuck.

### ISSUE THREAD

**Issue by gijsroge** [Intracto/buildozer#26]
If you have an error you in your sass files the build throws an error but does not recompile after you fix the issue. 

This forces you too re trigger the watch task each time you make a mistake.

Not sure whats causing this.

**Comment by MartijnCuppens** [comment]
Hmm, I can't reproduce that. Could you scope where things go wrong?

**Comment by gijsroge** [comment]
@MartijnCuppens yeah I was planning on debugging it. Just created an issue so I can keep track of the progress.

**Comment by gijsroge** [comment]
I've setup a repo where you can reproduce the issues.

Just run the buildozer watch command and uncomment https://github.com/gijsroge/plumber-sass-watch-issue/blob/master/scss/subfolder/_test.scss#L3

It only happens if you import a file from a subfolder that triggers an error ..  🤷‍♂️

Found a couple of related issues.
https://github.com/floatdrop/gulp-plumber/issues/34
https://github.com/floatdrop/gulp-plumber/issues/30
https://github.com/floatdrop/gulp-plumber/issues/42

The quick fix is to implement a custom errorHandler that emits an 'end' event.
https://github.com/floatdrop/gulp-plumber/issues/30#issuecomment-201737090

Looks like we have 2 options available.
Either we apply the quick fix
Or we could look into handling errors by ourself (https://gulpjs.com/docs/en/getting-started/async-completion#using-an-error-first-callback)

Whats your opinion?

**Comment by MartijnCuppens** [comment]
Maybe https://github.com/Intracto/buildozer/issues/22 causes this. I think we better figure out how to fix that issue first, solving that might solve this (not sure at all, but I know for sure are callbacks are currently not ok)

**Comment by MartijnCuppens** [comment]
This was actually solved by `async`ing the `cssCompile()` function in #32 🎉 https://github.com/Intracto/buildozer/blob/a285c2888187f9ae04d156177e72de56ab035caf/lib/gulp/css.js#L35

**Comment by gijsroge** [comment]
🎉 🎉
