### ISSUE TITLE
Check TypeScript integration possibilities

### ISSUE THREAD

**Issue by MartijnCuppens** [Intracto/buildozer#89]

**Comment by JanDC** [comment]
Guide: https://www.typescriptlang.org/docs/handbook/gulp.html

**Comment by MartijnCuppens** [comment]
Not going to look into this for the following reasons:
- Tried experimenting with this, but because of Gulp's specific architecture, compilation is rather slow (About 2s for a simple file while normal js compiles in several ms)
- Not sure how to handle imports, since the whole idea behind Buildozer is to make use of globbing to detect files.
- The basic implementation thus only supports typed variables
- Typescript is quite heavy to load by default
